### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mbmosher** [yoprogramo/QRcodeEink#1]
In arduino 2.0.0 I receive the following error wehn trying to compile the example:

In file included from /private/var/folders/5k/_vtvth091bj75_wp0hxtf7r80000gq/T/.arduinoIDE-unsaved202295-939-1j7t88p.a0sql/sketch_oct5a/sketch_oct5a.ino:9:
xxxxxxxx/Documents/Arduino/libraries/QRcodeEink/src/qrcodeeink.h:13:10: fatal error: GxGDE0213B72B/GxGDE0213B72B.h: No such file or directory
 #include <GxGDE0213B72B/GxGDE0213B72B.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1

**Comment by yoprogramo** [comment]
Hello,

Please take note that you need the library GxGDE0213B72B installed on your system.

Yo can obtain it in https://github.com/lewisxhe/GxEPD/tree/master/src/GxGDE0213B72B

Regards
